# Generated by Django 4.2.9 on 2024-05-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElectionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("epic_id", models.CharField(max_length=20)),
                ("transaction_no", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ElectionDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.IntegerField(default=0)),
                ("num_candidates", models.IntegerField(default=0)),
                ("candidate_ids", models.TextField(default="")),
                ("party_names", models.TextField(default="")),
                ("num_machines", models.IntegerField(default=0)),
                ("machine_ids", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="EpicIdData",
            fields=[
                (
                    "epic_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("allotted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "machine_no",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("location", models.CharField(max_length=100)),
                ("local_ip", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("firstname", models.CharField(default="", max_length=20)),
                ("lastname", models.CharField(default="", max_length=20)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("adhaar", models.BigIntegerField(primary_key=True, serialize=False)),
                ("email", models.EmailField(default="abc@ycce.in", max_length=254)),
                ("phone", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="ToggleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("election_toggle", models.BooleanField(default=False)),
                ("voter_registration_toggle", models.BooleanField(default=False)),
                ("candidate_registration_toggle", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("epic", models.CharField(default="0", max_length=20, unique=True)),
                ("fingerprint", models.CharField(default="0", max_length=1024)),
                ("status", models.CharField(default="0", max_length=50)),
                ("disability", models.BooleanField(default=False)),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="appapi.person"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("party", models.CharField(max_length=20)),
                (
                    "manifesto",
                    models.FileField(
                        blank=True,
                        default="default_pdf.pdf",
                        null=True,
                        upload_to="manifestos/",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default_image.jpg", null=True, upload_to="profile/"
                    ),
                ),
                ("accepted", models.BooleanField(default=False)),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="appapi.person"
                    ),
                ),
            ],
        ),
    ]
