# Generated by Django 4.2.9 on 2024-02-27 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="candidate",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="appapi.person"
            ),
        ),
    ]
