# Generated by Django 4.2.9 on 2024-02-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appapi", "0002_candidate_id_alter_candidate_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
