# Generated by Django 4.2.9 on 2024-02-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appapi", "0003_alter_candidate_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
