# Generated by Django 4.2.9 on 2024-03-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appapi", "0004_alter_candidate_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machine",
            name="id",
        ),
        migrations.AlterField(
            model_name="electiondata",
            name="transaction_no",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="machine",
            name="machine_no",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
