# Generated by Django 4.2.9 on 2024-03-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appapi", "0005_remove_machine_id_alter_electiondata_transaction_no_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToggleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("election_toggle", models.BooleanField(default=False)),
                ("voter_registration_toggle", models.BooleanField(default=False)),
                ("candidate_registration_toggle", models.BooleanField(default=False)),
            ],
        ),
    ]
