# Generated by Django 4.2.9 on 2024-03-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appapi", "0006_togglesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectionDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("num_candidates", models.IntegerField(default=0)),
                ("candidate_ids", models.TextField(default="")),
                ("party_names", models.TextField(default="")),
                ("num_machines", models.IntegerField(default=0)),
                ("machine_ids", models.TextField(default="")),
            ],
        ),
    ]
