# Generated by Django 4.2.9 on 2024-03-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appapi", "0007_electiondetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electiondetails",
            name="date",
            field=models.IntegerField(default=0),
        ),
    ]
