# Generated by Django 4.2.9 on 2024-03-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appapi", "0008_alter_electiondetails_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpicIdData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("epic_id", models.CharField(max_length=20)),
                ("allotted", models.BooleanField(default=False)),
            ],
        ),
    ]
